In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [6]:
# Create our features
# Convert string columns to numbers and drop 'loan_status' column then assign to X
X = pd.get_dummies(df, columns=['home_ownership', 'verification_status', 'issue_d', 'pymnt_plan', 
                'initial_list_status', 'next_pymnt_d', 'application_type', 'hardship_flag', 
                'debt_settlement_flag']).drop('loan_status', axis=1)

# Create our target
y = df['loan_status']
X.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,1,1,0,1,0,1,1,0,1,1

In [7]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [8]:
# Check the balance of our target values
df['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [10]:
# Check balances
print(Counter(y_train))
print(Counter(y_test))

Counter({'low_risk': 51352, 'high_risk': 260})
Counter({'low_risk': 17118, 'high_risk': 87})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [11]:
# Resample the training data with the BalancedRandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
rf_model = RandomForestClassifier(n_estimators=100, random_state=77) 
rf_model = rf_model.fit(X_train, y_train)
predictions = rf_model.predict(X_test)

In [12]:
# Calculated the balanced accuracy score
acc_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.9959895379250218

In [13]:
# Display the confusion matrix
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0           28           59
Actual 1           10        17108

In [14]:
# Calculated the balanced accuracy score
acc_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.9959895379250218

In [15]:
# Print the imbalanced classification report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

   high_risk       0.74      0.32      0.45        87
    low_risk       1.00      1.00      1.00     17118

    accuracy                           1.00     17205
   macro avg       0.87      0.66      0.72     17205
weighted avg       1.00      1.00      1.00     17205

In [16]:
# List the features sorted in descending order by feature importance
importances = rf_model.feature_importances_
importances
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.08636109560838232, 'total_rec_int'),
 (0.07821632132995758, 'total_rec_prncp'),
 (0.06610166426674943, 'total_pymnt_inv'),
 (0.06566721357200846, 'last_pymnt_amnt'),
 (0.04861200458012797, 'total_pymnt'),
 (0.020986083748073935, 'out_prncp_inv'),
 (0.019723683973363982, 'out_prncp'),
 (0.018284436560603787, 'installment'),
 (0.017471764345472488, 'mo_sin_old_rev_tl_op'),
 (0.017116953553201825, 'mo_sin_old_il_acct'),
 (0.015763336578520047, 'dti'),
 (0.015097021916257926, 'max_bal_bc'),
 (0.014735435760080278, 'annual_inc'),
 (0.014348363609830503, 'tot_hi_cred_lim'),
 (0.014080039373198206, 'total_bc_limit'),
 (0.013933798450280121, 'revol_bal'),
 (0.013383965263533868, 'bc_util'),
 (0.013054515478505137, 'tot_cur_bal'),
 (0.013010095479710715, 'bc_open_to_buy'),
 (0.012999028467500005, 'total_bal_ex_mort'),
 (0.012869885763858507, 'total_rec_late_fee'),
 (0.012752646141215032, 'loan_amnt'),
 (0.012713308468547364, 'il_util'),
 (0.0126281887214362, 'total_acc'),
 (0.012614785630926257, 'total_il_high_credit_limit'),
 (0.012068567567575642, 'total_rev_hi_lim'),
 (0.01188977414903924, 'avg_cur_bal'),
 (0.011572531234711634, 'int_rate'),
 (0.011479361580414169, 'total_bal_il'),
 (0.011166301291874176, 'mo_sin_rcnt_rev_tl_op'),
 (0.010892631380157631, 'all_util'),
 (0.01075754992991762, 'mths_since_rcnt_il'),
 (0.009999723120065284, 'mths_since_recent_inq'),
 (0.009581004513609633, 'mths_since_recent_bc'),
 (0.009517783829442218, 'issue_d_Mar-2019'),
 (0.009340179704782316, 'open_acc'),
 (0.009336620561226704, 'num_rev_accts'),
 (0.009214633802347931, 'mo_sin_rcnt_tl'),
 (0.009137929492197177, 'num_actv_rev_tl'),
 (0.008859394576697387, 'num_rev_tl_bal_gt_0'),
 (0.008668848416584059, 'num_il_tl'),
 (0.008526838141143408, 'total_cu_tl'),
 (0.008487549303173175, 'pct_tl_nvr_dlq'),
 (0.00841065265085969, 'acc_open_past_24mths'),
 (0.008407885252558055, 'num_bc_tl'),
 (0.007934927473780098, 'num_sats'),
 (0.00776249967012533, 'num_op_rev_tl'),
 (0.007701274354533719, 'percent_bc_gt_75'),
 (0.00719464948093031, 'open_rv_24m'),
 (0.007083141665337999, 'open_il_24m'),
 (0.007041634341963797, 'num_actv_bc_tl'),
 (0.0070407648306149906, 'inq_last_12m'),
 (0.006487539398242949, 'open_act_il'),
 (0.006457512775060506, 'num_tl_op_past_12m'),
 (0.006048133441052424, 'inq_fi'),
 (0.005940005495763861, 'open_acc_6m'),
 (0.005905040438389159, 'mort_acc'),
 (0.00581104601692221, 'num_bc_sats'),
 (0.005082497330018329, 'issue_d_Jan-2019'),
 (0.004785872258503177, 'inq_last_6mths'),
 (0.004782712863013833, 'open_rv_12m'),
 (0.0045838555455091695, 'delinq_2yrs'),
 (0.004566250722569031, 'open_il_12m'),
 (0.004436033667449502, 'issue_d_Feb-2019'),
 (0.0042699222796807644, 'next_pymnt_d_Apr-2019'),
 (0.004035321779297431, 'next_pymnt_d_May-2019'),
 (0.004007610896491686, 'tot_coll_amt'),
 (0.0035236904311194226, 'num_accts_ever_120_pd'),
 (0.0024861048454575953, 'pub_rec'),
 (0.002430804457738519, 'verification_status_Source Verified'),
 (0.0024098529413886668, 'verification_status_Not Verified'),
 (0.002366009029539671, 'pub_rec_bankruptcies'),
 (0.002289492745674358, 'verification_status_Verified'),
 (0.002059187929923932, 'home_ownership_OWN'),
 (0.0019576793835711093, 'application_type_Individual'),
 (0.0017899033059308527, 'home_ownership_MORTGAGE'),
 (0.0017625544170856828, 'application_type_Joint App'),
 (0.001746499696428813, 'num_tl_90g_dpd_24m'),
 (0.0015019235601438025, 'initial_list_status_w'),
 (0.0014169081869956572, 'collections_12_mths_ex_med'),
 (0.0012393490302713493, 'initial_list_status_f'),
 (0.0011907113002289332, 'home_ownership_RENT'),
 (0.000528411236523067, 'home_ownership_ANY'),
 (0.0005012736370092287, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [17]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
ee_model = RandomForestClassifier(n_estimators=100, random_state=77) 
ee_model = ee_model.fit(X_train, y_train)
ee_predictions = ee_model.predict(X_test)

In [18]:
# Calculated the balanced accuracy score
acc_score = accuracy_score(y_test, ee_predictions)
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.9959895379250218

In [19]:
# Display the confusion matrix
print(confusion_matrix(y_test, ee_predictions))

[[   28    59]
 [   10 17108]]

In [20]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, ee_predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.74      0.32      1.00      0.45      0.57      0.30        87
   low_risk       1.00      1.00      0.32      1.00      0.57      0.34     17118

avg / total       1.00      1.00      0.33      1.00      0.57      0.34     17205